### ISSUE TITLE
Actividad 1

### ISSUE THREAD

**Issue by PedroGarcia11439** [SistemasTecTlaxiaco/actividad-1-mapa-mental-PedroGarcia11439#1]
Actividad 1
Mapa Mental
1BS
[Mapa Mental Diagrama de Lluvia de Ideas con Formas Orgánicas Marrón.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-mapa-mental-PedroGarcia11439/files/9474660/Mapa.Mental.Diagrama.de.Lluvia.de.Ideas.con.Formas.Organicas.Marron.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De acuerdo a la rúbrica la calificación es 15%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
